- brand: DMC
  name: 
  - 'Natura XL'


- brand: Drops
  name: 
  - 'Safran'
  - 'Baby Merino Mix'

- brand: Hahn
  name: 
  - 'Alpacca Speciale'

- brand: Stylecraft
  name: 
  - 'Special double knit'